nearby service v1
EvilMindDevs/hms-sdk-unity pull request #76
Opened 2021-03-01 23:12 UTC by gmYusuf

### Nearby Service Added
- Android parts update for callback funtions
- Nearby Connection features added
**Main features**
- Broadcast and Scanning
- Managing Connections
- Data Transmission
 
**_https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/connection-preparations-0000001050040586-V5_**

2021-03-11 10:15 UTC, m0skit0 requested changes
- Consider properties where appropriate
- Remove wrapping of Java equals/hashcode
- Remove wrapping of Android Parcelable API
- Delete commented code
- Make sure you correctly wrap Java objects to C# ones
- Make sure visibility is correct, some fields can be private
- Please make sure all files end with newline so Git can work correctly
- Please preserve correct indentation and formatting

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Policy.cs
> +        }
Can directly use =>

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/PutOption.cs
> +        public static AndroidJavaObject Policy => androidJavaClass.Call<AndroidJavaObject>("getPolicy");
No wrappers for these Java objects?

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/PutOption.cs
> +            public Builder SetCallback(AndroidJavaObject callback) => Call<Builder>("setCallback", callback);
Not wrapped, can be properties

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +   public class StatusCallback : JavaObjectWrapper
Empty class?

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public Nearby(AndroidJavaObject javaObject) : base(javaObject) { }
Constructor not needed, this is a static class

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/StatusCode.cs
> +    public class StatusCode : JavaObjectWrapper
static class and not JavaObjectWrapper

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/StatusCode.cs
> +        public StatusCode(AndroidJavaObject javaObject) : base(javaObject) { }
No constructor needed

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +    public class Data : Parcelable
Why do we need Parcelable in C#?

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        private static readonly AndroidJavaClass DataClass = new AndroidJavaClass("com.huawei.hms.nearby.transfer.Data");
Different name than in other classes, please keep the same names

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/DataCallback.cs
> +public class DataCallback : JavaObjectWrapper
Not a JavaObjectWrapper

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiShareCallback.cs
> +        public void OnWifiShareResult(String endpointId, int statusCode) => androidJavaClass.Call("onWifiShareResult", endpointId, statusCode);
Calling instance method on java class

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiShareEngine.cs
> +                => androidJavaClass.Call<Task<Void>>("shareWifiConfig", endPointID);
Calling instance methods on Java class

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiSharePolicy.cs
> +   public  class WifiSharePolicy : JavaObjectWrapper
This looks like an enum but no enumeration provided

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/InputStream.cs
> +    public class InputStream : JavaObjectWrapper
Empty class, this is standard Java API

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/Parcel.cs
> +    public class Parcel : JavaObjectWrapper
Empty class, we don't need parecelables in C#

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/ParcelFileDescriptor.cs
> +    public class ParcelFileDescriptor : JavaObjectWrapper
Empty class, we don't need parecelables in C#

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/Parcelable.cs
> +    public class Parcelable : JavaObjectWrapper
Empty class, we don't need parecelables in C#

2021-03-11 10:15 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/UUID.cs
> +  public  class UUID : JavaObjectWrapper
Empty class?

2021-03-16 09:27 UTC, m0skit0 requested changes

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessagePicker.cs
> +        public String ToStringObject => Call<String>("toString");
Not needed

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessagePicker.cs
> +            public Builder IncludeAllTypes() => Call<Builder>("includeAllTypes");
Not wrapped

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Policy.cs
> +        public Policy() : base("com.huawei.hms.nearby.message.Policy") { }
This constructor seems a mistake, Policy can only be obtained through static properties?

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        }
- Why not just CallStaticAsWrapper?
- AndroidJavaObject should be specific C# class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/NearbyApiContext.cs
> +        public String GetApiKey => androidJavaClass.Call<String>("getApiKey");
Instance method using Java class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/NearbyApiContext.cs
> +                nearbyApiContextInstance = new NearbyApiContext(analyticsClassObject);
CallStaticAsWrapper

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/StatusCode.cs
> +        [UnityEngine.Scripting.Preserve]
Don't need to preserve

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        public Stream AsStream => androidJavaClass.CallStaticAsWrapper<Stream>("asStream");
Instance method using Java class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        public int DataType => androidJavaClass.Call<int>("getType");
Instance method using Java class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        public static Data FromFile(AndroidJavaObject pfd) => androidJavaClass.CallStaticAsWrapper<Data>("fromFile", pfd);
AndroidJavaObject should be specific C# class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        public static Data FromStream(AndroidJavaObject pfd) => androidJavaClass.CallStaticAsWrapper<Data>("fromStream", pfd);
AndroidJavaObject should be specific C# class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public Stream StreamFactory(AndroidJavaObject parcelFileDescriptor) => androidJavaClass.Call<Stream>("streamFactory", parcelFileDescriptor);
Uses Android Parecelable API, remove it

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public AndroidJavaObject AsInputStream => androidJavaClass.Call<AndroidJavaObject>("asInputStream");
- AndroidJavaObject should be specific C# class
- Instance method using Java class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public long Size => androidJavaClass.Call<long>("getSize");
- Instance method using Java class
- Not wrapped

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        public class Type : JavaObjectWrapper
static class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/TransferStateUpdate.cs
> +        public long GetTotalBytes => Call<long>("getTotalBytes");
Remove "Get", not needed for properties

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/TransferStateUpdate.cs
> +        public class Status
static class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiShareEngine.cs
> +                => CallAsWrapper<TaskVoidWrapper>("shareWifiConfig", endPointID);
Formatting

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiSharePolicy.cs
> +   public  class WifiSharePolicy
static class

2021-03-16 09:27 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Utils/AndroidJavaObjectExtensions.cs
> +}
Don't remove newline at end of file

2021-03-23 16:33 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectInfo.cs
> +        public bool IsRemoteConnect => androidJavaClass.Call<bool>("isRemoteConnect");
fixed

2021-03-25 09:22 UTC, m0skit0 requested changes

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectCallBack.cs
> +            {
Formatting please

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/Distance.cs
> +        public Distance() : base("com.huawei.hms.nearby.discovery.Distance") { }
Preserve

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/Policy.cs
> +        public Policy(AndroidJavaObject javaObject) : base(javaObject) { }
Preserve

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +        public BeaconId Parse(Message messsage) => androidJavaClass.CallStaticAsWrapper<BeaconId>("parse", messsage);
Instance method called through Java class

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +            AndroidJavaObject androidJavaObject = androidJavaClass.Call<AndroidJavaObject>("getBeaconUuid");
Instance method called through Java class

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +        public String BeaconUuid()
- Should be property
- No need for intermediate variable, just chain the call

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/GetOption.cs
> +        public GetCallback GetCallback => CallAsWrapper<GetCallback>("getCallback");
Remove "Get" from name

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Message.cs
> +        public byte[] Hex => Call<byte[]>("getContent");
Content, not Hex

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageHandler.cs
> +        public void OnLost(Message message) => androidJavaClass.Call("onLost", message);
Instance methods called through Java class

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessagePicker.cs
> +    {
Formatting

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Policy.cs
> +        public Policy(AndroidJavaObject javaObject) : base(javaObject) { }
Preserve

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +    private class StatusCallbackInterface : AndroidJavaProxy
Formatting

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public static WifiShareEngine GetWifiShareEngine(AndroidJavaObject context) => androidJavaClass.CallStaticAsWrapper<WifiShareEngine>("getWifiShareEngine", context);
Use wrapper class, not AndroidJavaObject

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/NearbyApiContext.cs
> +        }
Just return androidJavaClass.CallStaticAsWrapper<NearbyApiContext>("getInstance") directly, no need for caching instance.

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public File AsJavaFile => CallAsWrapper<File>("asJavaFile");
This looks wrong. I guess this returns JDK File type, and you are returning this same File type. You need to return C# runtime File type, if possible.

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +using System.Text;
Why are we using these?

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public static File FileFactory(File javaFile, long size) => androidJavaClass.Call<File>("fileFactory", javaFile, size);
This also looks wrong. I guess this takes JDK File type as parameter, not this same File type.

2021-03-25 09:22 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiSharePolicy.cs
> +    {
- Formatting
- Missing constructor?

2021-03-25 11:27 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessagingCallbackWrapper.cs
> +    public class AGConnectAppMessagingCallbackWrapper : AndroidJavaProxy
its cant be because AGConnectAppMessaging.AddOnDismissListener(Action<AppMessage, AGConnectAppMessagingCallbackWrapper.DismissType> onMessageClick) using as a parameter this

2021-03-25 11:32 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +        public BeaconId Parse(Message messsage) => androidJavaClass.CallStaticAsWrapper<BeaconId>("parse", messsage);
Parse(Message messsage) is static function because of that i used androidJavaClass object to call.

2021-03-25 11:33 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +        public String BeaconUuid()
done

2021-03-25 11:33 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageHandler.cs
> +        public void OnLost(Message message) => androidJavaClass.Call("onLost", message);
done

2021-03-25 12:23 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessagingCallbackWrapper.cs
> +    public class AGConnectAppMessagingCallbackWrapper : AndroidJavaProxy
Done

2021-03-25 12:23 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/Location.cs
> +        public Location(AndroidJavaObject javaObject) : base(javaObject) { }
Done

2021-03-25 12:23 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/MessageType.cs
> +        public MessageType(AndroidJavaObject javaObject) : base(javaObject) { }
Done

2021-03-25 12:25 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectCallBack.cs
> +            {
Done

2021-03-25 12:25 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/BleSignal.cs
> +        public BleSignal() : base("com.huawei.hms.nearby.discovery.BleSignal") { }
Done

2021-03-25 12:26 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/Distance.cs
> +        public Distance() : base("com.huawei.hms.nearby.discovery.Distance") { }
Done

2021-03-25 12:28 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +            AndroidJavaObject androidJavaObject = androidJavaClass.Call<AndroidJavaObject>("getBeaconUuid");
Done

2021-03-25 12:28 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/GetOption.cs
> +        public GetCallback GetCallback => CallAsWrapper<GetCallback>("getCallback");
done

2021-03-25 12:28 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Message.cs
> +        public byte[] Hex => Call<byte[]>("getContent");
done

2021-03-25 12:29 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessagePicker.cs
> +    {
done

2021-03-25 12:29 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Policy.cs
> +        public Policy(AndroidJavaObject javaObject) : base(javaObject) { }
done

2021-03-25 12:30 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +    private class StatusCallbackInterface : AndroidJavaProxy
done

2021-03-25 12:30 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public static WifiShareEngine GetWifiShareEngine(AndroidJavaObject context) => androidJavaClass.CallStaticAsWrapper<WifiShareEngine>("getWifiShareEngine", context);
done

2021-03-25 12:30 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public File AsJavaFile => CallAsWrapper<File>("asJavaFile");
done

2021-03-25 12:31 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +using System.Text;
done

2021-03-25 12:31 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +            public static File FileFactory(File javaFile, long size) => androidJavaClass.Call<File>("fileFactory", javaFile, size);
done

2021-03-29 09:42 UTC, m0skit0 requested changes

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void AddOnDismissListener(Action<AppMessage, DismissType> onMessageClick)
Parameter naming is wrong.

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void AddOnDisplayListener(Action<AppMessage> onMessageClick)
Parameter naming is wrong.

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/DissmissType.cs
> +        public DismissType(AndroidJavaObject javaObject) : base(javaObject) { }
Preserve

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectCallBack.cs
> +            public void onEstablish(string p0, ConnectInfo p1)
This is override of Java interface, will receive AndroidJavaObject, not ConnectInfo.

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectCallBack.cs
> +            public void onResult(string p0, ConnectResult p1)
This is override of Java interface, will receive AndroidJavaObject, not ConnectResult.

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/Policy.cs
> +        public Policy(AndroidJavaObject javaObject) : base(javaObject) { }
Formatting

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +        public BeaconId Parse(Message messsage) => androidJavaClass.CallStaticAsWrapper<BeaconId>("parse", messsage);
Then needs to be static in C# as well

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +            public StatusCallbackInterface(IStatusCallback listener) : base("org.m0skit0.android.hms.unity.nearby.StatusListener")
IStatusCallback can also be changed to Action<bool> since it is a functional interface

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public static WifiShareEngine GetWifiShareEngine() => androidJavaClass.CallStaticAsWrapper<WifiShareEngine>("getWifiShareEngine", AndroidContext.ApplicationContext);
All these can be properties, remove Get

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/NearbyApiContext.cs
> +        public String GetApiKey => Call<String>("getApiKey");
Property with get/set

2021-03-29 09:42 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/DataCallback.cs
> +        public DataCallbackInterface(IDataCallback listener) : base("org.m0skit0.android.hms.unity.nearby.DataListener")
IDataCallback can be transformed into 2 Actions.

2021-03-29 11:12 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/DataCallback.cs
> +        public DataCallbackInterface(IDataCallback listener) : base("org.m0skit0.android.hms.unity.nearby.DataListener")
DataCallback is abstract class because of that I use this style

2021-03-29 11:12 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/NearbyApiContext.cs
> +        public String GetApiKey => Call<String>("getApiKey");
done
![image](https://user-images.githubusercontent.com/8115505/112828789-d9e4a080-9098-11eb-8f25-ab803e6ee507.png)

2021-03-29 11:13 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public static WifiShareEngine GetWifiShareEngine() => androidJavaClass.CallStaticAsWrapper<WifiShareEngine>("getWifiShareEngine", AndroidContext.ApplicationContext);
done
![image](https://user-images.githubusercontent.com/8115505/112828820-e5d06280-9098-11eb-97b7-9119c8e22741.png)

2021-03-29 11:14 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +            public StatusCallbackInterface(IStatusCallback listener) : base("org.m0skit0.android.hms.unity.nearby.StatusListener")
done
![image](https://user-images.githubusercontent.com/8115505/112828904-ff71aa00-9098-11eb-9664-819c00c88436.png)

2021-03-29 11:15 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/DissmissType.cs
> +        public DismissType(AndroidJavaObject javaObject) : base(javaObject) { }
done

2021-03-29 11:15 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void AddOnDisplayListener(Action<AppMessage> onMessageClick)
done

2021-03-29 11:15 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void AddOnDismissListener(Action<AppMessage, DismissType> onMessageClick)
done

2021-03-29 11:29 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/DataCallback.cs
> +        public DataCallbackInterface(IDataCallback listener) : base("org.m0skit0.android.hms.unity.nearby.DataListener")
![image](https://user-images.githubusercontent.com/8115505/112829962-8bd09c80-909a-11eb-983a-3a4610d17d4d.png)

2021-03-29 11:29 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectCallBack.cs
> +            public void onResult(string p0, ConnectResult p1)
![image](https://user-images.githubusercontent.com/8115505/112830449-38128300-909b-11eb-8a78-2d58cf0b6086.png)

2021-03-29 11:30 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectCallBack.cs
> +            public void onEstablish(string p0, ConnectInfo p1)
![image](https://user-images.githubusercontent.com/8115505/112830479-3f399100-909b-11eb-911d-5f86406076c4.png)

2021-03-29 11:30 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/DissmissType.cs
> +        public DismissType(AndroidJavaObject javaObject) : base(javaObject) { }
![image](https://user-images.githubusercontent.com/8115505/112830511-4bbde980-909b-11eb-852b-346b6016743a.png)

2021-03-29 11:31 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void AddOnDisplayListener(Action<AppMessage> onMessageClick)
![image](https://user-images.githubusercontent.com/8115505/112830556-5ed0b980-909b-11eb-9e53-1da7fd946184.png)

2021-03-29 11:32 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiSharePolicy.cs
> +    {
![image](https://user-images.githubusercontent.com/8115505/112830707-917ab200-909b-11eb-9a22-54a6e9c0b403.png)

2021-03-29 11:33 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/NearbyApiContext.cs
> +        }
done

2021-03-30 07:29 UTC, m0skit0 requested changes

2021-03-30 07:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public AGConnectAppMessaging(AndroidJavaObject javaObject) : base(javaObject) { }
Preserve

2021-03-30 07:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void SetDisplayEnable(bool enable) => Call("setDisplayEnable", enable);
Property with get/set

2021-03-30 07:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void SetFetchMessageEnable(bool enable) => Call("setFetchMessageEnable", enable);
Property with get/set

2021-03-30 07:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void SetForceFetch() => Call("setForceFetch");
Set without value?

2021-03-30 07:29 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +    }
No method override of Java interface?

2021-03-30 07:36 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void SetDisplayEnable(bool enable) => Call("setDisplayEnable", enable);
![image](https://user-images.githubusercontent.com/8115505/112951161-bc204580-9143-11eb-8a19-77fe9615a99e.png)

2021-03-30 07:36 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public AGConnectAppMessaging(AndroidJavaObject javaObject) : base(javaObject) { }
![image](https://user-images.githubusercontent.com/8115505/112951211-c7737100-9143-11eb-9fe0-967ff92eea3c.png)

2021-03-30 07:37 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void SetFetchMessageEnable(bool enable) => Call("setFetchMessageEnable", enable);
![image](https://user-images.githubusercontent.com/8115505/112951347-eb36b700-9143-11eb-8546-11ec5b96a67c.png)

2021-03-30 07:39 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/AppMessaging/AGConnectAppMessaging.cs
> +        public void SetForceFetch() => Call("setForceFetch");
![image](https://user-images.githubusercontent.com/8115505/112951589-2fc25280-9144-11eb-8959-1239dd528269.png)
this one dont have parameter

2021-03-30 08:20 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/StatusCallback.cs
> +    }
![image](https://user-images.githubusercontent.com/8115505/112957308-fa206800-9149-11eb-8fff-88a66f4f4b8e.png)
done

2021-03-30 08:25 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public static WifiShareEngine GetWifiShareEngine() => androidJavaClass.CallStaticAsWrapper<WifiShareEngine>("getWifiShareEngine", AndroidContext.ApplicationContext);
![image](https://user-images.githubusercontent.com/8115505/112957890-921e5180-914a-11eb-8d9a-baac63d9608e.png)
all get names deleted

2021-03-30 08:32 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public static WifiShareEngine GetWifiShareEngine(AndroidJavaObject context) => androidJavaClass.CallStaticAsWrapper<WifiShareEngine>("getWifiShareEngine", context);
![image](https://user-images.githubusercontent.com/8115505/112958995-a878dd00-914b-11eb-8f8d-8f18f770f23c.png)

2021-03-30 08:37 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/WifiShare/WifiSharePolicy.cs
> +   public  class WifiSharePolicy
![image](https://user-images.githubusercontent.com/8115505/112959588-410f5d00-914c-11eb-8305-01a50bbbfbb3.png)

I am using as a parameter this class

![image](https://user-images.githubusercontent.com/8115505/112959641-4cfb1f00-914c-11eb-9374-6680c548dc64.png)

2021-03-30 08:39 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/TransferStateUpdate.cs
> +        public long GetTotalBytes => Call<long>("getTotalBytes");
![image](https://user-images.githubusercontent.com/8115505/112959909-92b7e780-914c-11eb-9af8-113921ab1b06.png)

2021-03-30 08:40 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Transfer/Data.cs
> +        public int DataType => androidJavaClass.Call<int>("getType");
![image](https://user-images.githubusercontent.com/8115505/112960015-ab280200-914c-11eb-919c-0071f624e4c2.png)

2021-03-30 08:42 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        public Nearby(AndroidJavaObject javaObject) : base(javaObject) { }
![image](https://user-images.githubusercontent.com/8115505/112960287-ef1b0700-914c-11eb-80a0-ec47ddb31876.png)

2021-03-30 08:47 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/PutOption.cs
> +            public Builder SetCallback(AndroidJavaObject callback) => Call<Builder>("setCallback", callback);
![image](https://user-images.githubusercontent.com/8115505/112960977-9dbf4780-914d-11eb-9712-805f6f4bf4a9.png)
Wrapper class

2021-03-30 08:48 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/PutOption.cs
> +        public static AndroidJavaObject Policy => androidJavaClass.Call<AndroidJavaObject>("getPolicy");
done

2021-03-30 08:50 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/PutOption.cs
> +        public static AndroidJavaObject Policy => androidJavaClass.Call<AndroidJavaObject>("getPolicy");
![image](https://user-images.githubusercontent.com/8115505/112961454-0efefa80-914e-11eb-90fc-d76102d54f76.png)

2021-03-30 08:50 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/PutOption.cs
> +        public static AndroidJavaObject Policy => androidJavaClass.Call<AndroidJavaObject>("getPolicy");
PutCallback is AndroidJavaProxy

2021-03-30 08:51 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/Policy.cs
> +        }
![image](https://user-images.githubusercontent.com/8115505/112961611-32c24080-914e-11eb-8a84-2464cb47c38e.png)

2021-03-30 08:52 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageOption.cs
> +            public Builder SetPermissions(int permissions) => Call<Builder>("setPermissions", permissions);
![image](https://user-images.githubusercontent.com/8115505/112961770-584f4a00-914e-11eb-8a66-48a33d1b5fcf.png)

2021-03-30 09:11 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageEngine.cs
> +        public Task<Void> Put(Message message) => androidJavaClass.Call<Task<Void>>("put", message);
![image](https://user-images.githubusercontent.com/8115505/112964441-022fd600-9151-11eb-80af-ab2f1dacaccc.png)

2021-03-30 09:11 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageHandler.cs
> +        public void OnLost(Message message) => androidJavaClass.Call("onLost", message);
![image](https://user-images.githubusercontent.com/8115505/112964497-0e1b9800-9151-11eb-953a-b92cbda2316b.png)

2021-03-30 09:12 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageHandler.cs
> +        public void OnLost(Message message) => androidJavaClass.Call("onLost", message);
![image](https://user-images.githubusercontent.com/8115505/112964609-28ee0c80-9151-11eb-956f-6f963b229f02.png)

2021-03-30 09:12 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/BroadcastOption.cs
> +        public bool Equals(JavaObjectWrapper javaObject) => androidJavaClass.Call<bool>("equals", javaObject);
done

2021-03-30 09:13 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/BroadcastOption.cs
> +            }
done

2021-03-30 09:13 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectInfo.cs
> +        //public static int CREATOR => androidJavaClass.GetStatic<int>("CREATOR");
done

2021-03-30 09:13 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectInfo.cs
> +        public int DescribeContents() => androidJavaClass.Call<int>("describeContents");
done

2021-03-30 09:13 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ConnectInfo.cs
> +        public bool IsRemoteConnect() => androidJavaClass.Call<bool>("isRemoteConnect");
![image](https://user-images.githubusercontent.com/8115505/112964865-605cb900-9151-11eb-8ed6-c59aa8d5972e.png)

2021-03-30 09:14 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/Policy.cs
> +        }
![image](https://user-images.githubusercontent.com/8115505/112964909-6bafe480-9151-11eb-8fb5-8f0d5121a9c0.png)

2021-03-30 09:14 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Discovery/ScanOption.cs
> +            }
![image](https://user-images.githubusercontent.com/8115505/112964975-7e2a1e00-9151-11eb-95b3-720df5b66f7c.png)

2021-03-30 09:15 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/BeaconId.cs
> +            public Builder SetHexInstance(String hexInstance) => Call<Builder>("setHexInstance", hexInstance);
![image](https://user-images.githubusercontent.com/8115505/112965021-8c783a00-9151-11eb-80eb-0b4692708721.png)

2021-03-30 09:15 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/GetOption.cs
> +        public static GetOption DEFAULT => androidJavaClass.GetStatic<GetOption>("DEFAULT");
![image](https://user-images.githubusercontent.com/8115505/112965092-9d28b000-9151-11eb-9870-21bf195992cd.png)

2021-03-30 09:15 UTC, gmYusuf commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Message/MessageHandler.cs
> +        public void OnLost(Message message) => androidJavaClass.Call("onLost", message, message);
![image](https://user-images.githubusercontent.com/8115505/112965161-ab76cc00-9151-11eb-8684-02fa47774e95.png)

2021-03-31 07:50 UTC, m0skit0 approved these changes

2021-03-31 07:50 UTC, m0skit0 commented on hms-sdk-unity/HuaweiMobileServices/Nearby/Nearby.cs
> +        [UnityEngine.Scripting.Preserve]
Preserve not needed here

2021-03-31 12:44 UTC, merged